# Generated by Django 4.2.6 on 2023-12-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emarket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartype",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="car_types"),
        ),
    ]
