# Generated by Django 4.2.6 on 2024-01-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emarket", "0003_alter_order_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dealership",
            name="clients",
            field=models.ManyToManyField(
                related_name="dealerships", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
