# Generated by Django 4.2.6 on 2024-01-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emarket", "0005_monosettings_order_invoice_id_order_invoice_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="invoice_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="invoice_url",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.CreateModel(
            name="OrderInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_id", models.CharField(max_length=100, null=True)),
                ("invoice_url", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(max_length=100, null=True)),
                (
                    "orders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="emarket.order",
                    ),
                ),
            ],
        ),
    ]
