# Generated by Django 4.2.6 on 2024-01-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emarket", "0006_remove_order_invoice_id_remove_order_invoice_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderinvoice",
            name="orders",
        ),
        migrations.AddField(
            model_name="orderinvoice",
            name="orders",
            field=models.ManyToManyField(related_name="orders", to="emarket.order"),
        ),
    ]
